### ISSUE TITLE
assertions give unhelpful error messages

### ISSUE THREAD

**Issue by lovasoa** [petgraph/fixedbitset#51]
When trying to create a fixedbitset with invalid parameters, here is the error message and stack trace that is generated : 

```
explanation = '''
Panic occurred in file '/home/[...]/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs' at line 13
'''
cause = 'assertion failed: start <= end && end <= length'
method = 'Panic'
backtrace = '''

   0: 0x5638b4ce3be5 - tokio::runtime::enter::exit::hba90552f0bd4dfed
   1: 0x5638b4cfb0d9 - tokio::task::blocking::block_in_place::h0a384439c8a047e1
   2: 0x5638b4d0cc52 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3fe07ad1656c20e0
   3: 0x5638b4ce8984 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h134d72015faf04e0
   4: 0x5638b4cd7b5f - tokio::runtime::task::harness::Harness<T,S>::poll::hcf7a7f0209ef9099
   5: 0x5638b5079d46 - std::thread::local::LocalKey<T>::with::hed4303faf3e1aed8
   6: 0x5638b506bb22 - tokio::runtime::thread_pool::worker::Context::run_task::hce41c119710e9437
   7: 0x5638b506b21e - tokio::runtime::thread_pool::worker::Context::run::h56ab1c1f681d7b07
   8: 0x5638b5076ad3 - tokio::macros::scoped_tls::ScopedKey<T>::set::hdf577aceeef82d4c
   9: 0x5638b506ad1b - tokio::runtime::thread_pool::worker::run::h961448ba1e9ff7ff
  10: 0x5638b4d17247 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h57e15455d5038c88
  11: 0x5638b4ce9359 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hec30f88dbe1bed0a
  12: 0x5638b4cd6806 - tokio::runtime::task::harness::Harness<T,S>::poll::h1a26a8b5f39df086
  13: 0x5638b506d5b7 - tokio::runtime::blocking::pool::Inner::run::h937eb2b632dbdb7b
  14: 0x5638b5071ce8 - tokio::runtime::context::enter::h29b8ab9636afe6c1
  15: 0x5638b506eb8f - std::sys_common::backtrace::__rust_begin_short_backtrace::h4a06a10cbf72246d
  16: 0x5638b507c192 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hef5eaf9a4d249daf
  17: 0x5638b51fbe6a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hf311c88f1fadb9b8
                at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/liballoc/boxed.rs:1076
                 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h8cfb7235b81393ef
                at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/liballoc/boxed.rs:1076
                 - std::sys::unix::thread::Thread::new::thread_start::hf745c8cf29a89648
                at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/sys/unix/thread.rs:87
  18: 0x7fe9d53fc609 - start_thread
  19: 0x7fe9d553e103 - clone
  20:        0x0 - <unresolved>'''
```
This doesn't even mention that the error comes from fixedbitset, or give any useful information that may help with debugging the issue.

Something that would help a lot would be to always use the second argument of `assert!` to give useful information about the assertion.

**Comment by jrraymond** [comment]
Thanks for opening an issue.

How are you calling the function? When I run 
```
fn main() {
    let mut y = fixedbitset::FixedBitSet::with_capacity(3);
    y.insert(3);

    println!("Hello, world!");
}
```
I see
```
thread 'main' panicked at 'assertion failed: bit < self.length', <::std::macros::panic macros>:2:4
...
 12: fixedbitset::FixedBitSet::insert
...
```
in the stack trace.

**Comment by lovasoa** [comment]
The problem is `assertion failed: bit < self.length', <::std::macros::panic macros>:2:4`

The message I posted comes from human_panic, used in dezoomify-rs, but this is not related. 

The PR I referenced above makes the error messages understandable.

**Comment by jrraymond** [comment]
The issue raise states that the assert error does not contain useful information such as the crate. But this is not true. In the small example above the error message contains the crate (`fixedbitset`), the function (`FixedBitSet::insert`), and the assertion that failed (`assertion failed: bit < self.length`). 

Are you building with `--release`? I think if you build with `--release`, some of the context information is lost. Try running you're code without `--release` and I think you will see a more helpful error message.

**Comment by lovasoa** [comment]
@jrraymond : Users do not run software in debug mode, so the bug reports they make will look like the first one I posted, not the one you mentioned. Is there any reason for not wanting to add descriptive error messages to your asserts ? This is a general good practice.

**Comment by jrraymond** [comment]
ah ok. Thanks for clarifying the stack trace is visible to users of an application. I wanted to make sure I understood your use case.
